config/routes.rb
Rails.application.routes.draw do
  root "blogposts#index"
  get "/blogposts", to: "blogposts#index"
  resources :blogposts do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blogpost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
	def index
		@blogposts = Blogpost.all
	end

	def show
		@blogpost = Blogpost.find(params[:id])
	end

	def new
		@blogpost = Blogpost.new
	end

	def create
		@blogpost = Blogpost.new(blogpost_params)

		if @blogpost.save
			redirect_to @blogpost
		else
			render :new
		end
	end

	def edit
		@blogpost = Blogpost.find(params[:id])
	end

	def update
		@blogpost = Blogpost.find(params[:id])

		if @blogpost.update(blogpost_params)
			redirect_to @blogpost
		else
			render :edit
		end
	end

	def destroy
		@blogpost = Blogpost.find(params[:id])
		@blogpost.destroy

		redirect_to root_path
	end

	private
	def blogpost_params
		params.require(:blogpost).permit(:title, :body)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.all
	end

	def create
		@blogpost = Blogpost.find(params[:blogpost_id])
		@comment = @blogpost.comments.create(comment_params)
		redirect_to blogpost_path(@blogpost)
	end

	private
	def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogposts/edit.html.erb
<h1>Edit blogpost</h1>

<%= form_with model: @blogpost do |form| %>
	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
		<% @blogpost.errors.full_messages_for(:title).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.label :body %><br>
		<%= form.text_field :body %>
		<% @blogpost.errors.full_messages_for(:body).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/blogposts/index.html.erb
<h1>Blog</h1>

<h3>Blogposts</h3>

<ul>
	<% @blogposts.each do |blogpost| %>
		<li>
			<%= link_to blogpost.title, blogpost %><br>
			<%= truncate(blogpost.body, length:50, separator: " ", omission: "... (Read more)") %>
		</li>
	<% end %>
</ul>

<%= link_to "Create new post", new_blogpost_path %>

app/views/blogposts/new.html.erb
<h1>Create new blogpost</h1>

<%= form_with model: @blogpost do |form| %>
	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
		<% @blogpost.errors.full_messages_for(:title).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.label :body %><br>
		<%= form.text_field :body %>
		<% @blogpost.errors.full_messages_for(:body).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/blogposts/show.html.erb
<h1><%= @blogpost.title %></h1>

<p><%= @blogpost.body %></p>

<%= link_to "Home", root_path %><br>
<%= link_to "Edit", edit_blogpost_path(@blogpost) %><br>
<%= link_to "Delete", blogpost_path(@blogpost), method: :delete %>

<h3>Create new comment</h3>

<%= form_with model: [@blogpost, @blogpost.comments.build] do |form| %>
	<div>
		<%= form.label :username %><br>
		<%= form.text_field :username %>
	</div>

	<div>
		<%= form.label :body %><br>
		<%= form.text_field :body %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>

<h3>Comments</h3>

<ul>
	<% Comment.all.each do |comment| %>
		<li>
			<h4><%= comment.username %></h4>
			<p><%= comment.body %></p>
		</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>